/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 cheese.glb
Author: Grasbock (https://sketchfab.com/grasbock)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cheese-6aca23ca300b474888ad72b00be9595d
Title: Cheese
*/

import { useGLTF } from "@react-three/drei";

export function Cheese(props) {
  const { nodes, materials } = useGLTF("assets/models/cheese.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/cheese.glb");
