// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 dog.glb
Author: Yury Misiyuk (https://sketchfab.com/Tim0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dog-a89b49b3d9c647a8805d8d5287f47f48
Title: Dog
*/

import { useGLTF } from "@react-three/drei";

export function Dog(props) {
  const { nodes, materials } = useGLTF("assets/models/dog.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes["037_Vray_Material_#32_0"].geometry}
        material={materials.Material_32}
        position={[-1.91, 12.044, 0.017]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/dog.glb");
